### PR TITLE
Add instructions for installing from source to README

### PR DESCRIPTION
**Pull request by mobyvb**
Add instructions for installing from source code to README

### CODE REVIEW

**Comment by paul-gauthier** [comment]
Good idea to document how to run it from source. The approach you suggest doesn't actually work for me. I usually do this:

```
pip3 install -e /path/to/checkout/of/aider
```

After that you can invoke `aider` as normal, but it will be running from the working directory of your checkout.

Let me know if you'd like to update the PR, or I can.

**Comment by mobyvb** [comment]
@paul-gauthier thanks for the reply. I'll can update the change later today

**Comment by mobyvb** [comment]
@paul-gauthier updated

**Comment by paul-gauthier** [comment]
Thanks for the PR!

**Pull request merged**
