### PR TITLE
add budget manager for openai, openrouter, anthropic, cohere, ai21, replicate, etc.

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hi @paul-gauthier @joshuavial ,

Noticed you're using openai + openrouter. I'm working on litellm (simple library to standardize LLM API Calls - https://github.com/BerriAI/litellm) and wanted to see how i could be helpful.

I added support for setting api budgets across all the providers we support (OpenAI, Openrouter, Anthropic, AI21, Cohere, Replicate, etc.) using our BudgetManager - https://docs.litellm.ai/docs/budget_manager.

Would love to know if this helps.

Happy to add additional documentation + testing if the initial PR looks good.

### CODE REVIEW

**Comment by paul-gauthier** [comment]
This is an interesting idea, and it looks like your litellm library might provide some nice hooks for doing budget management. But I'm not sure I am comfortable adopting a new package interposed in the LLM API. That's a pretty critical piece of code, which already has support for OpenAI, Azure and OpenRouter. It would require a lot of testing to adopt a new abstraction layer here.

Also this PR looks like it would immediately crash with `NameError` on undefined symbols?

**Comment by krrishdholakia** [comment]
but my pr doesn't change your LLM completion code - what am i missing here? @paul-gauthier

**Comment by paul-gauthier** [comment]
It doesn't look like you've ever attempted to run this code, let alone test it? The PR adds 7 lines of code and generates 8 undefined symbol errors.

```
aider/sendchat.py:7:1: F401 'litellm.BudgetManager' imported but unused
from litellm import BudgetManager
^
aider/sendchat.py:9:1: F821 undefined name 'budget_manager'
budget_manager.create_budget(total_budget=10, user="1234")
^
aider/sendchat.py:12:1: E402 module level import not at top of file
from openai.error import (
^
aider/sendchat.py:68:8: F821 undefined name 'budget_manager'
    if budget_manager.get_current_cost(user=user) < budget_manager.get_total_budget(user):
       ^
aider/sendchat.py:68:45: F821 undefined name 'user'
    if budget_manager.get_current_cost(user=user) < budget_manager.get_total_budget(user):
                                            ^
aider/sendchat.py:68:53: F821 undefined name 'budget_manager'
    if budget_manager.get_current_cost(user=user) < budget_manager.get_total_budget(user):
                                                    ^
aider/sendchat.py:68:85: F821 undefined name 'user'
    if budget_manager.get_current_cost(user=user) < budget_manager.get_total_budget(user):
                                                                                    ^
aider/sendchat.py:70:9: F821 undefined name 'budget_manager'
        budget_manager.update_cost(completion_obj=response, user=user)
        ^
aider/sendchat.py:70:51: F821 undefined name 'response'
        budget_manager.update_cost(completion_obj=response, user=user)
                                                  ^
aider/sendchat.py:70:66: F821 undefined name 'user'
        budget_manager.update_cost(completion_obj=response, user=user)
```

**Comment by paul-gauthier** [comment]
Looks like you're shotgunning PRs to dozens of repos.

https://github.com/pulls?q=is%3Apr+author%3Akrrishdholakia+support+

**Comment by krrishdholakia** [comment]
hi @paul-gauthier - happy to fix the runtime issues. 

Unclear though - why is the budget manager a bad idea - i'd appreciate any feedback you have on that. 

I can definitely work to ensure the initial change is more tested before making the PR - apologies for that.

**Pull request closed without merging**
