### PR TITLE
Typescript repo map fix

### PR DESCRIPTION
**Pull request by ryanfreckleton**
Corrects the query syntax for Tree Sitter TypeScript. This causes correct repo maps to be created. E.g. for the [nodeadr](https://github.com/robogeek/nodeadr) project:

```text
lib/client.ts:
⋮...
│import { ADRConnection } from './oadr.js';
⋮...
│export type AddReportOptions = {
│
│    /**
│     * The quantity that is being measured (enums.MEASUREMENTS).
│     * Optional for TELEMETRY_STATUS reports.
│     */
│    measurement?: types.Measurement;
│
│    /**
│     * Whether you want the data to be collected incrementally
⋮...
│export class OpenADRClient {
│
│    /**
│     * Initializes a new OpenADR Client (Virtual End Node)
│     * 
│     * @param ven_name The name for this VEN
│     * @param ven_id The ID for this VEN. If you leave this blank,
│     *               a VEN_ID will be assigned by the VTN.
│     * @param vtn_url The URL of the VTN (Server) to connect to
│     * @param cert The path to a PEM-formatted Certificate file to use
⋮...
│    set vtn_url(nu: string) { this.#vtn_url = nu; }
│    get vtn_url() { return this.#vtn_url; }
│
⋮...
│    async VTNConnection(): Promise<ADRConnection> {
│        if (this.#vtnconnection) {
│            return this.#vtnconnection;
│        }
│        // TODO must initialize the connection
│        this.#vtnconnection = new ADRConnection(this.vtn_url);
│        return this.#vtnconnection;
⋮...
│    async start() {
│        await this.create_party_registration();
│        if (!this.vtn_requested_poll_frequency) {
│            throw new Error(`start - no polling schedule supplied`);
│        }
│
│        this.#scheduler = new ToadScheduler();
│
│        const pollTask = new AsyncTask('VTN Poll', async (): Promise<void> => {
│            await this.poll();
⋮...
│    async handle_on_event(oadrDistributeEvent) {
│        if (typeof this.#receivedEvents === 'undefined') {
│            this.#receivedEvents = [];
│        }
│
│        for (const event of oadrDistributeEvent.oadrEvent) {
│            const eventDescriptor = event.eiEvent.eventDescriptor;
│
│            /*
│             * We're supposed to remove memory of the event. 
⋮...
│    on_event(callback) {
│        this.#handle_event = callback;
⋮...
│    handle_on_update_event() {
│        throw new Error(`Do not know what handle_on_update_event should do`);
│        // this.#handlers.emit('on_update_event') // TBD add arguments
⋮...
│    add_report(callback, resource_id: string, options: AddReportOptions) {
│
│        if (options.report_name && !enums.isReportName(options.report_name)) {
│            throw new Error(`add_report: ${options.report_name} is not a valid report name`);
│        }
│        if (options.reading_type && !enums.isReadingType(options.reading_type)) {
│            throw new Error(`add_report: ${options.reading_type} is not a valid reading type`);
│        }
│        if (options.report_type && !enums.isReportType(options.report_type)) {
│            throw new Error(`add_report: ${options.report_type} is not a valid report type`);
⋮...
│    query_registration() {
│
⋮...
│    async create_party_registration(): Promise<void> {
│        const requestID = uuidv4();
│        const request = await oadr_payload(
│            await render_template('oadrCreatePartyRegistration.xml', {
│            ven_id: this.ven_id,
│            ven_name: this.ven_name,
│            request_id: requestID,
│            profile_name: (await this.VTNConnection()).oadrProfile,
│            transport_name: 'simpleHttp',
│            /*
⋮...
│    request_event() {
│
⋮...
│    created_event() {
│
⋮...
│    create_report() {
│
⋮...
│    create_single_report() {
│
⋮...
│    update_report() {
│
⋮...
│    cancel_report() {
│        
⋮...
│    async poll() {
│        const request = await oadr_payload(
│            await render_template('oadrPoll.xml', {
│                ven_id: this.ven_id
│            })
│        );
│        
│        const response = await (await this.VTNConnection())
│                        .sendRequest('OadrPoll', request);
│
⋮...
```

Without these changes, the output from aider is as following:
```text

.gitignore

LICENSE

README.md

lib/client.ts

lib/enums.ts

lib/oadr.ts

lib/templates.ts

lib/types.ts

package.json

templates/README.md

tsconfig.json
```

### CODE REVIEW

**Comment by paul-gauthier** [comment]
I am a bit confused...

If I use your branch, I get *no* repomap on this popular typescript repo:

```
(aider) macbook:~/tmp$ git clone https://github.com/microsoft/TypeScript-Website
Cloning into 'TypeScript-Website'...

(aider) macbook:~/tmp$ cd TypeScript-Website/

(aider) macbook:tmp/TypeScript-Website$ aider --show-repo-map
Aider v0.24.2-dev-typescript-repo-map-fix
Model: gpt-4-0613 using diff edit format
Git repo: .git with 1,012 files
Warning: For large repos, consider using an .aiderignore file to ignore irrelevant files/dirs.
Repo-map: using 1024 tokens
100%|████████████████████████████████████████████████████| 1012/1012 [00:07<00:00, 141.49it/s]

(aider) macbook:tmp/TypeScript-Website$
```

If I use the main branch, I get a repomap (which seems a bit meager but is better than nothing):

```
(aider) macbook:tmp/TypeScript-Website$ rm -r .aider*

(aider) macbook:tmp/TypeScript-Website$ aider --show-repo-map
Aider v0.24.2-dev
Model: gpt-4-0613 using diff edit format
Git repo: .git with 1,012 files
Warning: For large repos, consider using an .aiderignore file to ignore irrelevant files/dirs.
Repo-map: using 1024 tokens
100%|████████████████████████████████████████████████████| 1012/1012 [00:04<00:00, 212.93it/s]
Below here are summaries of files present in the user's git repository.
Do not propose changes to these files, they are *read-only*.
To make a file *read-write*, ask the user to *add it to the chat*.

packages/playground-examples/copy/en/JavaScript/External APIs/TypeScript with React.tsx:
⋮...
│export interface Props {
│  /** The user's name */
│  name: string;
│  /** Should the name be rendered in bold */
│  priority?: boolean;
⋮...

packages/tsconfig-reference/scripts/types.ts:
⋮...
│export interface DiagnosticMessage {
│  key: string;
│  category: ts.DiagnosticCategory;
│  code: number;
│  message: string;
│  reportsUnnecessary?: {};
│  /* @internal */
│  elidedInCompatabilityPyramid?: boolean;
⋮...

packages/typescriptlang-org/src/components/layout/SiteFooter-PlaygroundSamples.tsx:
⋮...
│interface Props {
│  lang: string
⋮...
```

**Comment by paul-gauthier** [comment]
I agree with your results on the `nodeadr` repo. Your branch produces a much better repo map.

But I am concerned that the repo map disappeared on the `TypeScript-Website` repo.

**Comment by ryanfreckleton** [comment]
Ouch! That's a bad regression. Thank you for testing it against some other popular repositories.

With its current behavior on the TypeScript-Website repository, I don't think it's ready to merge into main. I'll add it to my heap to do some more tweaking and testing to see if we can't better behavior everywhere.

**Comment by ryanfreckleton** [comment]
@paul-gauthier I have revised this to include the prior queries that show things in the TypeScript Website repository. It now seems to do better on nodeadr with no regression on the Website repository. Please let me know if there's anything else I should do on this one.

**Pull request merged**
