### PR TITLE
RFC - Allow adding a github issue to chat context

### PR DESCRIPTION
**Pull request by omri123**
Hi, would you like to take a look on this feature?

In the first commit I changed Coder to allow adding arbitrary additional context in the begining of the chat.
In the second commit I used this infra to add github issues to the chat.

I didn't add a new command, instead I extended `/add` to allow `/add \issue-3`.
The feature is disabled by default and enabled with a flag. If enabled, the user need to supply github repository name and authentication token.

Thanks
Omri

### CODE REVIEW

**Comment by omri123** [comment]
Manually rebased above main

**Comment by paul-gauthier** [comment]
Thanks for putting this together. I think I would rather implement support for `/add url` and just make github issues be just another url you could add as additional context? But maybe there's a benefit to first class support for github issues?

**Comment by ryanpeach** [comment]
I like the idea of /add url. With maybe a specialization for github issues in the future.

**Comment by paul-gauthier** [comment]
I actually just merged `/web <url>` into the main branch. This will scrape the url and turn it into fairly clean markdown and then add it to the chat. 

The change is available in the main branch. You can get it by installing the latest version from github:

```
python -m pip install --upgrade git+https://github.com/paul-gauthier/aider.git
```

If you have a chance to try it, let me know if it works for you.

**Comment by omri123** [comment]
Sound like a great solution. Closing the issue

**Pull request closed without merging**
