### PR TITLE
docs: Add instructions on using Claude via Vertex AI

### PR DESCRIPTION
**Pull request by zxkxyz**
Added some basic instructions on how to get Claude models working through Vertex AI. Aider has support but there are currently no docs to indicate this great integration.

See #1044 for info that inspired this PR.

@sholub89

### CODE REVIEW

**Comment by paul-gauthier** [comment]
Thanks, I copied your content into a page for Vertex. It's going up now.

**Comment by sholub89** [comment]
@zxkxyz , @paul-gauthier please add the command to run using the mentioned files like so:
```
aider --config .aider.conf.yml
```
otherwise it isn't clear how to use them

**Comment by paul-gauthier** [comment]
https://aider.chat/docs/llms/vertex.html

**Comment by sholub89** [comment]
Perfect. Thank you @paul-gauthier , @zxkxyz

**Pull request closed without merging**
