### PR TITLE
DMTarmey/issue161

### PR DESCRIPTION
**Pull request by DMTarmey**
I would like for you to look  at my fixes to see if they work and are worth inclding in you main base code

### CODE REVIEW

**Review by DMTarmey — COMMENTED** [review]
test repomap.py was not working now it is

**Comment by paul-gauthier** [comment]
Hi DMTarmey,

Thanks for putting together this PR. Unfortunately, it contains almost a hundred files from your local environment.

Are you able to more clearly indicate the problem you are seeing with testing and the solution you are proposing?

**Comment by DMTarmey** [comment]
sorry ill take a look and ill submit the 1 file for you to look at I'm just finding vs code a little difficult at time still learning how to use it correctly.

**Comment by paul-gauthier** [comment]
I'm going to close this for now, but feel free to re-open if you have changes to discuss.

**Pull request closed without merging**
