### PR TITLE
fix: add gemini models

### PR DESCRIPTION
**Pull request by nobu007**
Just add difinitions for gemini models.

### CODE REVIEW

**Comment by mihow** [comment]
Thanks @nobu007! Where is the 2 billion token context window specified in the config?

**Comment by paul-gauthier** [comment]
Thanks for your interest in aider. 

These changes aren't needed to use the Gemini models. This doc may be helpful:

https://aider.chat/docs/llms/gemini.html

**Comment by mihow** [comment]
Thanks @paul-gauthier, are there docs about what information about the codebase that Aider adds to the context? It seems like the 1M & 2M token context window of the new Gemini models could fundamentally change the approach of what gets sent and when (e.g. send the whole codebase if it fits and use context caching).

**Comment by paul-gauthier** [comment]
https://aider.chat/docs/faq.html#how-can-i-add-all-the-files-to-the-chat

**Comment by nobu007** [comment]
@paul-gauthier 
Thanks for information.
Is it any plan for gemini-1.5-flash? Or already able to use anything other than gemini-1.5-pro available?
The flash one has someting functionally limit compare than pro.
So, I want to know about intentionally limitation or not.

**Comment by paul-gauthier** [comment]
The new gemini models were added this morning in v0.54.0.

I'm going to close this issue for now, but feel free to add a comment here and I will re-open or file a new issue any time.

**Comment by nobu007** [comment]
Just for information
https://github.com/paul-gauthier/aider/commit/12bb17fe638518416762bca30572a6031674b23e

**Pull request closed without merging**
