### PR TITLE
Add fzf file selection via pyfzf

### PR DESCRIPTION
**Pull request by tastyblob**
This implements the workflow of https://github.com/paul-gauthier/aider/issues/492 using pyfzf. What it doesn't do it yet is respect .aiderignore entries, but I first wanted to check if there's general interest in implementing something along those lines.

### CODE REVIEW

**Comment by paul-gauthier** [comment]
I know fzf is a popular tool, but I'm not likely to add it as a dependency for aider. I work very hard to make sure it is easy to install aider, avoiding extra platform specific install steps if possible.

Also, it appears that you could easily use a shell script wrapper to achieve the functionality in this PR, without needing to modify aider at all.

**Comment by tastyblob** [comment]
My bad, I repressed the fact that fzf is still required to be preinstalled. Definitely shouldn't be a prerequisite for running aider.

**Comment by maelp** [comment]
You could perhaps add a python setup.py option, eg `pip install aider[fzf]` for those who want it?

**Comment by tastyblob** [comment]
> You could perhaps add a python setup.py option, eg `pip install aider[fzf]` for those who want it?

That would require deterministic detection and interaction of various package manager + operating system flavors and their respective idiosyncrasies, besides handling the usually required privilege escalation (`sudo`) for package installs. It would probably only end in tears in the long run

**Comment by tastyblob** [comment]
I guess middle ground could be a conditional check for an existing fzf installation on aider program start and only then properly exposing the "--fzf" flag.

**Comment by maelp** [comment]
Not really if you use pyfzf, and you let the user ensure on his own (he knows what he is doing) that the fzf binary is installed

**Comment by maelp** [comment]
eg, if the user knows he has fzf installed, and then chooses to use `pip install aider[fzf]` it installs pyfzf

**Pull request closed without merging**
