### PR TITLE
List and switch models during chat session

### PR DESCRIPTION
**Pull request by joshuavial**
Add /models /model /m commands to list available models and switch in same chat session

based off #401 from @fire17

### CODE REVIEW

**Comment by fire17** [comment]
Awesome to see progress being made!
Does this include model autocomplete?

Waiting to see this pushed, thanks and all the best!

Ps. Is there an aider discord or collaborator meetings? I'd love to participate

**Comment by fire17** [comment]
@joshuavial happy you liked the alias idea :)
Thanks for the improvements, Hoping to see this merged
All the best!

**Comment by joshuavial** [comment]
I'm still intending to get to this at some stage @paul-gauthier but struggling to prioritise it.

**Comment by fire17** [comment]
I thought you made your own version already....

Also isn't this a classical task for Aider itself.. don't understand why it should take long, and hotswapping models during a run, is so important and useful

@joshuavial @paul-gauthier

**Pull request closed without merging**
